DongHo/Areas/Admin/Controllers/CompanyController.cs
using DongHo.DataAcess.IRepository;
using DongHo.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DongHo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            var datalist = _unitOfWork.Company.GetAll();
            return Json(new { data = datalist });
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Company model)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Company.Add(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Thêm thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public IActionResult Update(int? id)
        {
            var data = _unitOfWork.Company.GetFirstOrDefault(a => a.Id == id);
            if(data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Company company)
        {
           if(ModelState.IsValid)
            {
                _unitOfWork.Company.Update(company);
                _unitOfWork.Save();
                TempData["Succes"] = "Cập nhập thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var data = _unitOfWork.Company.GetFirstOrDefault(a => a.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            else
            {
                _unitOfWork.Company.Remove(data);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Xoá thành công" });
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

DongHo/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DongHo.Model;
using DongHo.DataAcess.IRepository;

namespace WebDongHo.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public  IActionResult Index()
        {
            var data = _unitOfWork.CoverType.GetAll();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType model)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Thêm thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
           
        }

        public  IActionResult Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var data =  _unitOfWork.CoverType.GetFirstOrDefault(a => a.Id == id);
            if(data==null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit(CoverType model)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Cập nhập thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public  IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var data = _unitOfWork.CoverType.GetFirstOrDefault(a => a.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var data = _unitOfWork.CoverType.GetFirstOrDefault(a => a.Id == id);
            if(data==null)
            {
                return NotFound();
            }
           else
            {
                _unitOfWork.CoverType.Remove(data);
                _unitOfWork.Save();
                TempData["Succes"] = "Xoá thành công";
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

DongHo/Areas/Admin/Views/Company/Create.cshtml
@model Company

<form method="post" asp-action="Create" >
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create Company</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StreetAddress">StreetAddress</label>
            <input asp-for="StreetAddress" class="form-control" />
            <span asp-validation-for="StreetAddress" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Ward">Ward</label>
            <input asp-for="Ward" class="form-control" />
            <span asp-validation-for="Ward" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="District">District</label>
            <input asp-for="District" class="form-control" />
            <span asp-validation-for="District" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Province">Province</label>
            <input asp-for="Province" class="form-control" />
            <span asp-validation-for="Province" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PhoneNumber">PhoneNumber</label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" @*onclick="return ValidateInput()"*@>
            Create
        </button>


        <a asp-action="Index" asp-controller="Company">Back</a>
    </div>
</form>

DongHo/Areas/Admin/Views/Company/Index.cshtml
<partial name="_NoficationPartial">
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2> Company List</h2>
            </div>
            <div class="col-6">
                <a asp-controller="Company" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus"></i>Create
                </a>
            </div>
        </div>
    </div>
    <table class="table table-bordered" id="tblData">
        <thead>
            <tr>
                <th> Name </th>
                <th> Adress </th>
                <th> District </th>
                <th> Province </th>
                <th> PhoneNumber </th>
                <th></th>
            </tr>
        </thead>
        @*<tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            <div>
                                <a class="btn btn-primary" asp-controller="CoverType" asp-action="Edit" asp-route-id=@item.Id><i class="bi bi-pencil"></i></a>
                                <a class="btn btn-danger" asp-controller="CoverType" asp-action="Delete" asp-route-id=@item.Id><i class="bi bi-trash"></i></a>
                            </div>

                        </td>
                    </tr>
                }

            </tbody>*@
    </table>
    @section Scripts{
        <script src="~/js/company.js"></script>
    }

DongHo/Areas/Admin/Views/Company/Update.cshtml
@model Company

<form method="post" asp-action="Update">
    <input hidden asp-for="Id"/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Edit Company</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StreetAddress">StreetAddress</label>
            <input asp-for="StreetAddress" class="form-control" />
            <span asp-validation-for="StreetAddress" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Ward">Ward</label>
            <input asp-for="Ward" class="form-control" />
            <span asp-validation-for="Ward" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="District">District</label>
            <input asp-for="District" class="form-control" />
            <span asp-validation-for="District" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Province">Province</label>
            <input asp-for="Province" class="form-control" />
            <span asp-validation-for="Province" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PhoneNumber">PhoneNumber</label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" @*onclick="return ValidateInput()"*@>
            Update
        </button>


        <a asp-action="Index" asp-controller="Company">Back</a>
    </div>
</form>