DongHo/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DongHo.Model;
using DongHo.DataAcess.IRepository;

namespace WebDongHo.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public  IActionResult Index()
        {
            var data = _unitOfWork.Brand.GetAll();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Brand model)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.Brand.Add(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Thêm thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
           
        }

        public  IActionResult Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var data =  _unitOfWork.Brand.GetFirstOrDefault(a => a.Id == id);
            if(data==null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit(Brand model)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.Brand.Update(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Cập nhập thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public  IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var data = _unitOfWork.Brand.GetFirstOrDefault(a => a.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var data = _unitOfWork.Brand.GetFirstOrDefault(a => a.Id == id);
            if(data==null)
            {
                return NotFound();
            }
           else
            {
                _unitOfWork.Brand.Remove(data);
                _unitOfWork.Save();
                TempData["Succes"] = "Xoá thành công";
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

DongHo/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DongHo.Model;
using DongHo.DataAcess.IRepository;

namespace DongHo.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public  IActionResult Index()
        {
            var data = _unitOfWork.Category.GetAll();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category model)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.Category.Add(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Thêm thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
           
        }

        public  IActionResult Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var data =  _unitOfWork.Category.GetFirstOrDefault(a => a.Id == id);
            if(data==null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit(Category model)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.Category.Update(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Cập nhập thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var data = _unitOfWork.Category.GetFirstOrDefault(a => a.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var data = _unitOfWork.Category.GetFirstOrDefault(a => a.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            else
            {
                _unitOfWork.Category.Remove(data);
                _unitOfWork.Save();
                TempData["Succes"] = "Xoá thành công";
                return RedirectToAction(nameof(Index));
            }
        }

        //[HttpDelete]
        //public IActionResult Delete(int? id)
        //{
        //    var data = _unitOfWork.Category.GetFirstOrDefault(a => a.Id == id);
        //    if(data==null)
        //    {
        //        return NotFound();
        //    }
        //    else
        //    {
        //        _unitOfWork.Category.Remove(data);
        //        _unitOfWork.Save();
        //        return Json(new { success = true, message = "Xoá thành công" });
        //    }    

        //}
    }
}

DongHo/Areas/Admin/Controllers/CompanyController.cs
using DongHo.DataAcess.IRepository;
using DongHo.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DongHo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            var datalist = _unitOfWork.Company.GetAll();
            return Json(new { data = datalist });
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Company model)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Company.Add(model);
                _unitOfWork.Save();
                TempData["Succes"] = "Thêm thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public IActionResult Update(int? id)
        {
            var data = _unitOfWork.Company.GetFirstOrDefault(a => a.Id == id);
            if(data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Company company)
        {
           if(ModelState.IsValid)
            {
                _unitOfWork.Company.Update(company);
                _unitOfWork.Save();
                TempData["Succes"] = "Cập nhập thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var data = _unitOfWork.Company.GetFirstOrDefault(a => a.Id == id);
            if (data == null)
            {
                return NotFound();
            }
            else
            {
                _unitOfWork.Company.Remove(data);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Xoá thành công" });
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

DongHo/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;
using DongHo.Model;
using DongHo.Model.ViewModels;
using DongHo.DataAcess.IRepository;
using DongHo.Utility;

namespace WebDongHo.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public  IActionResult Index()
        {
            var data = _unitOfWork.Product.GetAll();
            return View(data);
        }
       public IActionResult Upsert(int? id)
        {

            ProductVM productVM = new ProductVM();
            productVM.product = new Product();
            productVM.CategoryList = _unitOfWork.Category.GetAll().Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });
            productVM.CoverTypeList = _unitOfWork.CoverType.GetAll().Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });
            productVM.BrandList = _unitOfWork.Brand.GetAll().Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });
            //if (id==null || id ==0)
            //{
               
            //    return View(productVM);
            //}
            //else
            //{
            //    productVM.product = _unitOfWork.Product.GetFirstOrDefault(a => a.Id == id);
            //}
            return View(productVM);
        }

        #region viewbag
        //public IActionResult Upsert(int? id)
        //{
        //    Product product = new Product();
        //    IEnumerable<SelectListItem> categoryList = _unitOfWork.Category.GetAll().Select(a => new SelectListItem()
        //    {
        //        Text = a.Name,
        //        Value = a.Id.ToString()
        //    });

        //    IEnumerable<SelectListItem> coverTypeList = _unitOfWork.CoverType.GetAll().Select(a => new SelectListItem()
        //    {
        //        Text = a.Name,
        //        Value = a.Id.ToString()
        //    });
        //    IEnumerable<SelectListItem> brandList = _unitOfWork.Brand.GetAll().Select(a => new SelectListItem()
        //    {
        //        Text = a.Name,
        //        Value = a.Id.ToString()
        //    });
        //    if (id == null || id == 0)
        //    {
        //        ViewBag.CategoryList = categoryList;
        //        ViewBag.CoverTypeList = coverTypeList;
        //        ViewBag.BrandList = brandList;
        //        return View(product);
        //    }
        //    else
        //    {

        //    }
        //    return View(product);
        //}
        #endregion

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM)
        {

            if(ModelState.IsValid)
            {
                string webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;   
                _unitOfWork.Product.Add(productVM.product);
                
                //else
                //{
                //    _unitOfWork.Product.Update(productVM.product);
                //}
                _unitOfWork.Save();

                if (files.Count > 0)
                {
                    var uploads = Path.Combine(webRootPath, "images");
                    var extension = Path.GetExtension(files[0].FileName);

                    using (var filesStream = new FileStream(Path.Combine(uploads, productVM.product.Id + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filesStream);
                    }
                    productVM.product.ImageUrl = @"\images\" + productVM.product.Id + extension;
                }
                else
                {
                    var uploads = Path.Combine(webRootPath, @"images\" + SD.test);
                    System.IO.File.Copy(uploads, webRootPath + @"\images\" + productVM.product.Id + ".png");
                    productVM.product.ImageUrl = @"\images\" + productVM.product.Id + ".png";

                }
                _unitOfWork.Save();
                TempData["Succes"] = "Thêm thành công";
                return RedirectToAction(nameof(Index));
            }
            return View(productVM);
        }


        public IActionResult Update(int? id)
        {

            ProductVM productVM = new ProductVM();
            //productVM.product = new Product();
            productVM.product = _unitOfWork.Product.GetFirstOrDefault(a => a.Id == id);
            productVM.CategoryList = _unitOfWork.Category.GetAll().Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });
            productVM.CoverTypeList = _unitOfWork.CoverType.GetAll().Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });
            productVM.BrandList = _unitOfWork.Brand.GetAll().Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });          
          
            return View(productVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ProductVM productVM)
        {           
                string webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
            //_unitOfWork.Product.Update(productVM.product);

            //_unitOfWork.Save();
            var imageFromDb = _unitOfWork.Product.GetFirstOrDefault(a => a.Id == productVM.product.Id);
                if (files.Count > 0)
                {
                    var uploads = Path.Combine(webRootPath, "images");
                    var extension = Path.GetExtension(files[0].FileName);

                    var imagePath = Path.Combine(webRootPath, imageFromDb.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                    using (var filesStream = new FileStream(Path.Combine(uploads, productVM.product.Id + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filesStream);
                    }
                    productVM.product.ImageUrl = @"\images\" + productVM.product.Id + extension;
                }
                else
                {
                    var uploads = Path.Combine(webRootPath, @"images\" + SD.test);
                    System.IO.File.Copy(uploads, webRootPath + @"\images\" + productVM.product.Id + ".png");
                    productVM.product.ImageUrl = @"\images\" + productVM.product.Id + ".png";

                }
                _unitOfWork.Product.Update(productVM.product);
                _unitOfWork.Save();
                TempData["Succes"] = "Cập nhập thành công";
                return RedirectToAction(nameof(Index));
            
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CoverType,Brand");
            return Json(new { data = productList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var data = _unitOfWork.Product.GetFirstOrDefault(a => a.Id == id);
            if(data ==null)
            {
                return NotFound();
            }
            else
            {
                string webRootPath = _webHostEnvironment.WebRootPath;
                if (data.ImageUrl!=null)
                {
                   
                    
                    var imagePath = Path.Combine(webRootPath, data.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }
                _unitOfWork.Product.Remove(data);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Xoá thành công" });
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

DongHo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]DongHo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link href="~/css/bootswatch.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.2/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebDongHo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <form class="d-flex" data-dashlane-rid="c3cf84b274f5d9c8" data-form-type="">
                        <input class="form-control me-sm-2" type="search" placeholder="Search" data-dashlane-rid="0de2cda0b8ba56a0" data-form-type="">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit" data-dashlane-rid="733617ccc6e09b88" data-form-type="" data-dashlane-label="true">Search</button>
                    </form>
                </div>

                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                        <a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a>
                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                    </div>
                </div>
                <partial name="_LoginPartial">
            </div>
        </nav>



    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;  DongHo <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/0637z43g2vopl3tng2wfxtoad1i9cns9v76wra8isy1fpu4x/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

DongHo/Views/Shared/_NoficationPartial.cshtml
@if (TempData["Succes"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["Succes"]')
    </script>
}